[package]
name = "trs80m1-rs-core"
version = "0.2.0"
authors = ["Marek Benc <dusxmt@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
